#!/bin/bash

# Check if ENV.production is true
if [ "$PRODUCTION" = "true" ]
then
    # If true, run the desired command
    echo "PRODUCTION: $ENV"
    echo "Running jampack ./dist..."
    yarn jampack
else
    echo "PRODUCTION: $ENV"
    echo "Not running jampack. PRODUCTION is not true."
fi