#!/bin/bash
if [ "$PRODUCTION" = "true" ]
then
    echo "PRODUCTION: $ENV"
    echo "Running jampack ./dist..."
    yarn jampack
else
    echo "PRODUCTION: $ENV"
    echo "Not running jampack. PRODUCTION is not true."
fi